-- CREATION DE LA BASE DE DONNEES SAMA_ECOLE

CREATE DATABASE SAMA_ECOLE;

-- UTILISATION DE LA BASE DE DONNEES SAMA_ECOLE

USE SAMA_ECOLE;

-- CREATION DE LA TABLE Ecole         

CREATE TABLE ECOLE(
	EcoleID INT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL, 
	adresse  VARCHAR(100) NOT NULL, 
	email VARCHAR(30) UNIQUE NOT NULL,
	telephone VARCHAR(20) UNIQUE NOT NULL
);

-- CREATION DE LA TABLE STATUT 

CREATE TABLE STATUT (StatutID INT  PRIMARY KEY, 
poste VARCHAR(30) NOT NULL, 
categorie VARCHAR(30) NOT NULL
); 

-- pour afficher la structure d'une table on exécute la commande suivante :
EXEC sp_columns STATUT;

-- CREATION DE LA TABLE PERSONNEL

CREATE TABLE PERSONNEL ( PersonnelID INT PRIMARY KEY, 
nom VARCHAR(30) NOT NULL ,
prenom VARCHAR(30) NOT NULL, 
adresse VARCHAR(50) NOT NULL,
sexe VARCHAR(20) NOT NULL, 
telephone VARCHAR(30) UNIQUE NOT NULL, 
email VARCHAR(30) UNIQUE NOT NULL

/*
 EcoleID INT,
 StatutID INT,
    CONSTRAINT fk_ecole_id FOREIGN KEY (EcoleID) REFERENCES ECOLE(EcoleID),
    CONSTRAINT fk_statut_id FOREIGN KEY (StatutID) REFERENCES STATUT(StatutID)
	*/
); 

ALTER TABLE PERSONNEL 
	ADD EcoleID INT;

ALTER TABLE PERSONNEL
	ADD StatutID INT;

ALTER TABLE PERSONNEL
	ADD CONSTRAINT fk_ecole_id FOREIGN KEY (EcoleID) REFERENCES ECOLE(EcoleID);
ALTER TABLE PERSONNEL
	ADD CONSTRAINT fk_statut_id FOREIGN KEY (StatutID) REFERENCES STATUT(StatutID);

-- CREATION DE LA TABLE ELEVE
CREATE TABLE ELEVE (
	EleveID INT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
	prenom VARCHAR(50) NOT NULL,
	date_naissance DATE NOT NULL,
	sexe VARCHAR(30) NOT NULL,
	adresse VARCHAR(30) NOT NULL,
	telephone VARCHAR(30) UNIQUE NOT NULL,
	email VARCHAR(30) UNIQUE NOT NULL
);

-- CREATION DE LA TABLE ANNEE_SCOLAIRE

CREATE TABLE ANNEE_SCOLAIRE(
	 Annee_scolaireID INT PRIMARY KEY,
	 ANNEE VARCHAR(9) NOT NULL
);
	
-- CREATION DE LA TABLE NIVEAU 

CREATE TABLE NIVEAU (
    NiveauID INT PRIMARY KEY,
	Libelle VARCHAR(15) NOT NULL
);

--CREATION DE LA TABLE MATIERE

CREATE TABLE MATIERE(
    MatiereID INT PRIMARY KEY,
	Libelle VARCHAR(50) NOT NULL

);
--CREATION DE LA TABLE SERIE

CREATE TABLE SERIE(
    SerieID INT PRIMARY KEY,
	Libelle varchar(10) NOT NULL
);

--CREATION DE LA TABLE COEFFICIENT

CREATE TABLE COEFFICIENT(
     CoefficientID INT PRIMARY KEY,
	 Valeur INT CHECK(Valeur>0 AND Valeur<10) NOT NULL
);

--CREATION DE LA TABLE COEF_MATIERE

CREATE TABLE COEF_MATIERE(
     MatiereID INT NOT NULL,
	 NiveauID INT NOT NULL,
	 SerieID INT NOT NULL,
	 CoefficientID INT NOT NULL,
	 CONSTRAINT pk_coefmatiere PRIMARY KEY(MatiereID,NiveauID,SerieID,CoefficientID),
	 CONSTRAINT fk_matiere FOREIGN KEY(MatiereID) REFERENCES Matiere(MatiereID),
	 CONSTRAINT fk_niveau FOREIGN KEY(NiveauID) REFERENCES Niveau(NiveauID),
	 CONSTRAINT fk_serie FOREIGN KEY(SerieID) REFERENCES Serie(SerieID),
	 CONSTRAINT fk_coefficient FOREIGN KEY(CoefficientID) REFERENCES Coefficient(CoefficientID)

);
